In [5]:
#!pip install numpy

In [6]:
[1, 2, 3, 4] + [ 5, 6, 7, 8]

[1, 2, 3, 4, 5, 6, 7, 8]

In [7]:
import numpy as np

## Creating Arrays

In [8]:
data = np.array([1, 2, 3])
data

array([1, 2, 3])

In [9]:
type(data)

numpy.ndarray

In [10]:
data.dtype

dtype('int64')

In [11]:
data.ndim

1

In [12]:
data.shape

(3,)

In [13]:
data.size

3

In [14]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [15]:
zeros = np.zeros(3)
zeros

array([0., 0., 0.])

In [16]:
full = np.full(6,100.)
full

array([100., 100., 100., 100., 100., 100.])

In [17]:
np.diag((4, 4, 3, 7), 2)

array([[0, 0, 4, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 7],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [18]:
rand = np.random.random(3)
rand

array([0.48923437, 0.93641154, 0.35638724])

In [19]:
rand = np.random.randint(5, size=3)
rand 

array([1, 1, 0])

In [20]:
rang = np.arange(0, 10)
rang

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## Array Arithmetic

In [22]:
data

array([1, 2, 3])

In [23]:
ones

array([1., 1., 1.])

In [24]:
ones + data

array([2., 3., 4.])

In [25]:
list(ones) + list(data)

[np.float64(1.0),
 np.float64(1.0),
 np.float64(1.0),
 np.int64(1),
 np.int64(2),
 np.int64(3)]

In [26]:
ones - data

array([ 0., -1., -2.])

In [27]:
ones * data

array([1., 2., 3.])

In [28]:
ones / data

array([1.        , 0.5       , 0.33333333])

In [29]:
ones / 2

array([0.5, 0.5, 0.5])

In [30]:
#data / zeros
zeros / data

array([0., 0., 0.])

In [31]:
data

array([1, 2, 3])

In [32]:
ones

array([1., 1., 1.])

In [33]:
v = np.vstack((data, ones)) 
v

array([[1., 2., 3.],
       [1., 1., 1.]])

In [34]:
h = np.hstack((data, ones)) 
h

array([1., 2., 3., 1., 1., 1.])

In [35]:
np.hsplit(h, 2)

[array([1., 2., 3.]), array([1., 1., 1.])]

In [36]:
a

NameError: name 'a' is not defined

In [ ]:
b

array([[1., 1., 1.]])

In [ ]:
np.hsplit(v, 3)

[array([[1.],
        [1.]]),
 array([[2.],
        [1.]]),
 array([[3.],
        [1.]])]

In [ ]:
v

## Indexing

In [ ]:
data

array([1, 2, 3])

In [ ]:
data[0]

1

In [ ]:
data[0:1]

array([1])

In [ ]:
data[1:]

array([2, 3])

In [ ]:
lst = [1, 2, 3]

In [ ]:
lst[1:]

[2, 3]

In [ ]:
lst[1]

2

## Aggregation

In [ ]:
data

array([1, 2, 3])

In [ ]:
ones

array([1., 1., 1.])

In [ ]:
print(np.mean(data))
print(np.max(data))
np.min(data)

2.0
3


1

## In more dimensions

In [ ]:
ones = np.ones((3, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
zeros = np.zeros((3, 2))
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
rand = np.random.random((3, 2))
rand

array([[0.28308181, 0.48741361],
       [0.63938907, 0.00441386],
       [0.8122672 , 0.85353533]])

In [ ]:
data = np.array([[1,2],[3,4], [11, 12]])
data

array([[ 1,  2],
       [ 3,  4],
       [11, 12]])

In [ ]:
data.shape

(3, 2)

In [ ]:
data.ndim

2

In [ ]:
#---

In [ ]:
data

array([[ 1,  2],
       [ 3,  4],
       [11, 12]])

In [ ]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
data * ones

array([[ 1.,  2.],
       [ 3.,  4.],
       [11., 12.]])

In [ ]:
data + ones

array([[ 2.,  3.],
       [ 4.,  5.],
       [12., 13.]])

In [ ]:
rand, rand.shape

(array([[0.28308181, 0.48741361],
        [0.63938907, 0.00441386],
        [0.8122672 , 0.85353533]]),
 (3, 2))

In [ ]:
data.T, data.T.shape

(array([[ 1,  3, 11],
        [ 2,  4, 12]]),
 (2, 3))

In [ ]:
result = rand.dot(data.T)
result

array([[ 1.25790904,  2.79889989,  8.96286328],
       [ 0.64821678,  1.93582264,  7.08624608],
       [ 2.51933785,  5.8509429 , 19.17736308]])

In [ ]:
## ----

In [ ]:
data

array([[ 1,  2],
       [ 3,  4],
       [11, 12]])

In [ ]:
data[0:6:3, 1]
# data[0:4:2 , 1]

array([2])

In [ ]:
# ---

In [ ]:
data

array([[ 1,  2],
       [ 3,  4],
       [11, 12]])

In [ ]:
data.sum()

33

In [ ]:
data.max()

12

In [ ]:
data.max(axis=1)

array([ 2,  4, 12])

In [ ]:
data.min(axis=0)

array([1, 2])

In [ ]:
# ---

In [ ]:
rand

array([[0.28308181, 0.48741361],
       [0.63938907, 0.00441386],
       [0.8122672 , 0.85353533]])

In [ ]:
rand.T

array([[0.28308181, 0.63938907, 0.8122672 ],
       [0.48741361, 0.00441386, 0.85353533]])

In [ ]:
rand.reshape(4,2 )

ValueError: cannot reshape array of size 6 into shape (4,2)

In [ ]:
rand.reshape(4, )

ValueError: cannot reshape array of size 6 into shape (4,)

In [ ]:
result

array([[ 1.25790904,  2.79889989,  8.96286328],
       [ 0.64821678,  1.93582264,  7.08624608],
       [ 2.51933785,  5.8509429 , 19.17736308]])

In [ ]:
result = result.reshape(9,1)
result

array([[ 1.25790904],
       [ 2.79889989],
       [ 8.96286328],
       [ 0.64821678],
       [ 1.93582264],
       [ 7.08624608],
       [ 2.51933785],
       [ 5.8509429 ],
       [19.17736308]])

In [ ]:
result = result.reshape(-1,)
result

array([ 1.25790904,  2.79889989,  8.96286328,  0.64821678,  1.93582264,
        7.08624608,  2.51933785,  5.8509429 , 19.17736308])

In [ ]:
result

array([[ 1.25790904,  2.79889989,  8.96286328],
       [ 0.64821678,  1.93582264,  7.08624608],
       [ 2.51933785,  5.8509429 , 19.17736308]])

In [ ]:
con = result > 1.1
s = np.where(con, result, 0)
s

array([[ 1.25790904,  2.79889989,  8.96286328],
       [ 0.        ,  1.93582264,  7.08624608],
       [ 2.51933785,  5.8509429 , 19.17736308]])

In [ ]:
# ---

In [ ]:
np.ones((2, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
y_predictions = np.random.random((3, 1))
y_predictions

In [ ]:
y = np.random.random((3, 1))
y

In [ ]:
# To do

In [ ]:
n = labels.shape[0]
1/n * np.sum(np.square(predictions - labels))

In [ ]:
y_hat = np.array([1,2,4, 6])
y = np.array([1,0,5, 6])

In [ ]:
np.mean((y_hat - y)**2)