In [3]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [17]:
x = np.ones((4,2))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [21]:
y = np.zeros((4,2))
y

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

## Q#3: Add x and y arrays.

In [23]:
x+y

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [37]:
print("Array's Size is:" ,x.size) #array's size

print("Array's Shape is:",x.shape) #array's shape

print("Array's Dimension is:",x.ndim) #array's dimension

print("Array's Data Type is:",x.dtype) #array's data type



Array's Size is: 8
Array's Shape is: (4, 2)
Array's Dimension is: 2
Array's Data Type is: float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [51]:
w=np.array([[11,12],
            [13,14],
            [15,16]]) 
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [73]:
z=np.array([[1],[2],[3]]) #so we could combine it with w
z 

array([[1],
       [2],
       [3]])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [119]:
newArray=np.hstack((z, w)) 
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [79]:
    for row in newArray:
        for x in row:
            print(x)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [121]:
newArray[::-1, ::-1]

array([[16, 15,  3],
       [14, 13,  2],
       [12, 11,  1]])

## Q#10: Decrement all elements of "newArray" with 1.

In [129]:
newArray=newArray-1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [131]:
print(newArray.max())
print(newArray.min())

15
0


## Q#12: Print the first row of "newArray" using indexing.

In [133]:
newArray[0]

array([ 0, 10, 11])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [135]:
newArray[1][1]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [139]:
print(newArray[0][0])
print(newArray[1][2])

0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [141]:
newArray.reshape(9,1)

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [171]:
#The elements are 9 and this will cause an error so we will be reshaping it to 3,3
newArray.reshape(3,3)


array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

# Well Done 🎉