# Q1: Import numpy library

In [1]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [2]:
sequencefloat = np.linspace(0, 1, 15)

print(sequencefloat)

[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [4]:

arr1 = [1.1 , 2.1 , 3.1]
arr2 = [4.1 , 5.1 , 6.1]
arr3 = [7.1 , 8.1 , 9.1]
arr4 = [10.1 , 11.1 , 12.1]


array_3D = np.array([ [arr1, arr2], 
                       [arr3, arr4] ])

print(array_3D)


[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [8]:
print("The type of array_3D :" ,type(array_3D))

The type of array_3D : <class 'numpy.ndarray'>


In [7]:
print("The type of elements datatype :" ,array_3D.dtype)

The type of elements datatype : float64


In [9]:
print("The shape of data :" ,array_3D.shape)

The shape of data : (2, 2, 3)


In [10]:
print("The size of data :" ,array_3D.size)

The size of data : 12


In [13]:
print("The dimention of data :" ,array_3D.ndim)

The dimention of data : 3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [16]:
array_4D = array_3D.reshape(1, 2, 2, 3) 
print("New Array (4D):")
print(array_4D)
print("the array dimention :" ,array_4D.ndim)
print("the array shape " ,array_4D.shape)


New Array (4D):
[[[[ 1.1  2.1  3.1]
   [ 4.1  5.1  6.1]]

  [[ 7.1  8.1  9.1]
   [10.1 11.1 12.1]]]]
the array dimention : 4
the array shape  (1, 2, 2, 3)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [20]:
intger =  array_4D.astype(int) 
print("Integer Array (4D):\n"  ,intger)


Integer Array (4D):
 [[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [23]:
print("All elements:")
for element in np.nditer(intger):
    print(element)

All elements:
1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [26]:

number_8 = intger[0, 1, 0, 1] 

print("Number 8:", number_8)

Number 8: 8


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [27]:

number_5 = intger[0, 0, 1, 1]  
print("Number 5:", number_5)

number_6 = intger[0, 0, 1, 2] 
print("Number 6:", number_6)


Number 5: 5
Number 6: 6


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [28]:

index_8 = np.where(intger == 8)

print("Index of number 8:", index_8)

Index of number 8: (array([0]), array([1]), array([0]), array([1]))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [32]:
reshapeArray = intger.reshape(2,3,2)

print("Reshaped Array: \n" ,reshapeArray)

Reshaped Array: 
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [43]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

joined_array = np.concatenate((arr1, arr2),axis=None)
print("Array Without Axis: \n" , joined_array)


Array Without Axis: 
 ['A' 'B' 'E' 'F' 'C' 'D' 'G' 'H']


# Q12.2: Join the arrays along rows with axis = 1 

In [40]:

joined_array = np.concatenate((arr1, arr2), axis=1)  
print("Joined Array Along Rows (axis=1):")
print(joined_array)


Joined Array Along Rows (axis=1):
[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [41]:
split_arrays = np.split(joined_array, 2, axis=1)  

print("First Split Array:\n" , split_arrays[0])
print("Second Split Array:\n",split_arrays[1])


First Split Array:
 [['A' 'B']
 ['E' 'F']]
Second Split Array:
 [['C' 'D']
 ['G' 'H']]
