In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [2]:
# Creating an array of ones
x = np.ones(5)  # Change 5 to any desired size

print(x)


[1. 1. 1. 1. 1.]


## Q#2: Create y array with elements equal to 0.

In [3]:
# Creating an array of zeros
y = np.zeros(5)  # Change 5 to any desired size

print(y)


[0. 0. 0. 0. 0.]


## Q#3: Add x and y arrays.

In [4]:

# Creating x and y arrays
x = np.ones(5)  # Array of ones
y = np.zeros(5)  # Array of zeros

# Adding x and y
result = x + y

print(result)


[1. 1. 1. 1. 1.]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [5]:


# Creating x array
x = np.ones(5)  # Change 5 to any desired size

# Printing characteristics
print("Dimension:", x.ndim)       # Number of dimensions
print("Shape:", x.shape)          # Shape of the array
print("Size:", x.size)            # Number of elements
print("Data type:", x.dtype)      # Data type of elements


Dimension: 1
Shape: (5,)
Size: 5
Data type: float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [6]:
# Creating a 2D array w
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])

print(w)


[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [7]:

# Creating z array with numbers from 1 to 3
z = np.arange(1, 4)  # 4 is exclusive

print(z)


[1 2 3]


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [8]:
# Creating z array
z = np.arange(1, 4).reshape(3, 1)  # Reshaping to (3,1) for proper horizontal stacking

# Creating w array
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])

# Combining z and w horizontally
newArray = np.hstack((z, w))

print(newArray)


[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]


## Q#8: Print all elements of "newArray" using the loop.

In [9]:


# Creating newArray (if not already created)
z = np.arange(1, 4).reshape(3, 1)
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])
newArray = np.hstack((z, w))

# Printing elements using nested loops
for row in newArray:
    for elem in row:
        print(elem, end=" ")
    print()  # Newline after each row


1 11 12 
2 13 14 
3 15 16 


## Q#9: Reverse the columns and rows of "newArray".

In [10]:


# Creating newArray
z = np.arange(1, 4).reshape(3, 1)
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])
newArray = np.hstack((z, w))

# Reversing both rows and columns
reversedArray = newArray[::-1, ::-1]

print(reversedArray)


[[16 15  3]
 [14 13  2]
 [12 11  1]]


## Q#10: Decrement all elements of "newArray" with 1.

In [12]:


# Creating newArray 
z = np.arange(1, 4).reshape(3, 1)
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])
newArray = np.hstack((z, w))

# Decrementing all elements by 1
newArray -= 1

print(newArray)


[[ 0 10 11]
 [ 1 12 13]
 [ 2 14 15]]


## Q#11: Find smallest and biggest values in "newArray".

In [14]:


# Creating newArray (if not already created)
z = np.arange(1, 4).reshape(3, 1)
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])
newArray = np.hstack((z, w))

# Finding smallest and biggest values
smallest_value = np.min(newArray)
biggest_value = np.max(newArray)

print("Smallest value:", smallest_value)
print("Biggest value:", biggest_value)


Smallest value: 1
Biggest value: 16


## Q#12: Print the first row of "newArray" using indexing.

In [15]:


# Creating newArray (if not already created)
z = np.arange(1, 4).reshape(3, 1)
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])
newArray = np.hstack((z, w))

# Printing the first row
first_row = newArray[0]  # Index 0 represents the first row

print("First row:", first_row)


First row: [ 1 11 12]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [16]:


# Creating newArray (if not already created)
z = np.arange(1, 4).reshape(3, 1)
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])
newArray = np.hstack((z, w))

# Finding and printing the number 12 using indexing
number_12 = newArray[0, 2]  # First row (index 0), third column (index 2)

print("Number at the specified index:", number_12)


Number at the specified index: 12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [17]:


# Creating newArray (if not already created)
z = np.arange(1, 4).reshape(3, 1)
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])
newArray = np.hstack((z, w))

# Decrementing all elements by 1 (if required from Q#10)
newArray -= 1  

# Accessing the numbers 0 and 13 using indexing
num_0 = newArray[0, 0]  # First row, first column
num_13 = newArray[1, 2]  # Second row, third column

print("Number 0:", num_0)
print("Number 13:", num_13)


Number 0: 0
Number 13: 13


## Q#15: Change the shape of "newArray" to (9,1).

In [18]:


# Creating newArray (if not already created)
z = np.arange(1, 4).reshape(3, 1)
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])
newArray = np.hstack((z, w))

# Reshaping newArray to (9,1)
newArray = newArray.reshape(9, 1)

print("Reshaped newArray:\n", newArray)


Reshaped newArray:
 [[ 1]
 [11]
 [12]
 [ 2]
 [13]
 [14]
 [ 3]
 [15]
 [16]]


## Q#16: Change the shape of "newArray" to (3,2).

In [19]:


# Creating newArray (if not already created)
z = np.arange(1, 4).reshape(3, 1)
w = np.array([[11, 12],
              [13, 14],
              [15, 16]])
newArray = np.hstack((z, w))

# Selecting the first 6 elements and reshaping to (3,2)
newArray_subset = newArray.flatten()[:6].reshape(3, 2)

print("Reshaped newArray (3,2):\n", newArray_subset)


Reshaped newArray (3,2):
 [[ 1 11]
 [12  2]
 [13 14]]


# Well Done 🎉