In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [11]:
x=np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [15]:
y =np.zeros((3,3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [17]:
x + y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [128]:
print('The dimension of x:',x.ndim)
print('The Shape of x:',x.shape)
print('The Size of x:',x.size)
print('The Type of x:',type(x))

The dimension of x: 2
The Shape of x: (3, 3)
The Size of x: 9
The Type of x: <class 'numpy.ndarray'>


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [57]:
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [59]:
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [108]:
newArray = np.hstack((z.reshape(-1,1),w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [69]:
for row in  newArray:
    for elemint in row:
        print(elemint)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [80]:
 newArray.T

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [110]:
newArray = newArray - 1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [96]:
print('The smallest values:',np.min(newArray))
print('The biggest values:',np.max(newArray))

The smallest values: 1
The biggest values: 16


## Q#12: Print the first row of "newArray" using indexing.

In [112]:
newArray[0]

array([ 0, 10, 11])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [114]:
newArray[1,1]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [120]:
zero_value = newArray[0, 0]  
thirteen_value = newArray[1, 2] 

print(f"Element with value 0: {zero_value}")
print(f"Element with value 13: {thirteen_value}")

Element with value 0: 0
Element with value 13: 13


## Q#15: Change the shape of "newArray" to (9,1).

In [124]:
newArray.reshape(9,1)

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [126]:
newArray.reshape(3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉