In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [2]:
# write your code here ^_^
x=np.ones(3)
x

array([1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [3]:
# write your code here ^_^
y=np.zeros(3)
y

array([0., 0., 0.])

## Q#3: Add x and y arrays.

In [4]:
# write your code here ^_^
x + y

array([1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [5]:
# write your code here ^_^
print(x) , 
print(x.ndim) 
print(x.shape)
print(x.size) 
type(x)

[1. 1. 1.]
1
(3,)
3


numpy.ndarray

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [6]:
# write your code here ^_^
w = np.array([[11, 12], [13, 14], [15, 16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [7]:
# write your code here ^_^
z=np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [8]:
# write your code here ^_^
new_z=z.reshape(-1, 1)
print(new_z)
newArray=np.hstack((w,new_z))
newArray

[[1]
 [2]
 [3]]


array([[11, 12,  1],
       [13, 14,  2],
       [15, 16,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [9]:
# write your code here ^_^
for i in newArray:
    for y in i:
        print(y)

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [10]:
# write your code here ^_^
newArray.T

array([[11, 13, 15],
       [12, 14, 16],
       [ 1,  2,  3]])

## Q#10: Decrement all elements of "newArray" with 1.

In [11]:
# write your code here ^_^
print(newArray)
newArray-=1
newArray

[[11 12  1]
 [13 14  2]
 [15 16  3]]


array([[10, 11,  0],
       [12, 13,  1],
       [14, 15,  2]])

## Q#11: Find smallest and biggest values in "newArray".

In [12]:
# write your code here ^_^
newArray.max() ,newArray.min()

(np.int64(15), np.int64(0))

## Q#12: Print the first row of "newArray" using indexing.

In [13]:
# write your code here ^_^
first_row=newArray[0]
print(first_row)

[10 11  0]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [14]:
# write your code here ^_^
num_12=newArray[1][0]
print(num_12)

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [15]:
# write your code here ^_^
num_0=newArray[0][2] 
num_13=newArray[1][1]
print(num_0)
print(num_13)

0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [16]:
# write your code here ^_^
print(newArray)
y=newArray.reshape(9,1)
print(y)

[[10 11  0]
 [12 13  1]
 [14 15  2]]
[[10]
 [11]
 [ 0]
 [12]
 [13]
 [ 1]
 [14]
 [15]
 [ 2]]


## Q#16: Change the shape of "newArray" to (3,2).

In [17]:
# write your code here ^_^
newArray.reshape((3, 2))


ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉