# Q1: Import numpy library

In [2]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function



In [3]:
sequence = np.linspace(0, 1, 15)
print(sequence)

[0.         0.07142857 0.14285714 0.21428571 0.28571429 0.35714286
 0.42857143 0.5        0.57142857 0.64285714 0.71428571 0.78571429
 0.85714286 0.92857143 1.        ]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [6]:
arr = np.array([[1.1, 2.1, 3.1],
                 [4.1, 5.1, 6.1],
                 [7.1, 8.1, 9.1],
                 [10.1, 11.1, 12.1]])

arr3d = arr.reshape(2, 2, 3)
print(arr3d)

[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [8]:
print(type(arr3d))
print(arr3d.dtype)
print(arr3d.shape)
print(arr3d.size)
print(arr3d.ndim) 

<class 'numpy.ndarray'>
float64
(2, 2, 3)
12
3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [9]:
arr4d = arr3d.reshape(1, 2, 2, 3)
print(arr4d.ndim)
print(arr4d.shape)

4
(1, 2, 2, 3)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [10]:
arr_int = arr4d.astype(int)
print(arr_int)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [11]:
for i in np.nditer(arr_int):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [13]:
print(arr_int[1, 1, 1])

IndexError: index 1 is out of bounds for axis 0 with size 1

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [14]:
print(arr_int[0, 1, 1:3])

[[10 11 12]]


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [15]:
v = np.where(arr_int == 8)
print(v)

(array([0], dtype=int64), array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [11]:
reshape_arr = np.array([[[1, 2],
                             [3, 4],
                             [5, 6]],

                            [[7, 8],
                             [9, 10],
                             [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [17]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

joined_arr = np.concatenate((arr1, arr2))



# Q12.2: Join the arrays along rows with axis = 1 

In [18]:
joined_arr_axis1 = np.concatenate((arr1, arr2), axis=1)

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [19]:
split_arr = np.split(joined_arr, 2, axis=1) 