In [3]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [4]:
x = np.ones(3)

## Q#2: Create y array with elements equal to 0.

In [5]:
y = np.zeros(3)

## Q#3: Add x and y arrays.

In [6]:
np.add(x,y)

array([1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [7]:
x.shape , x.size , x.dtype , x.ndim

((3,), 3, dtype('float64'), 1)

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [8]:
w = np.array([[11, 12], [13, 14], [15, 16]])


## Q#6: Create z array contains the numbers from 1 to 3.

In [9]:
z = np.array([1,2,3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [10]:
z = z.reshape(-1, 1)
newArray =np.hstack((w,z))
print(newArray)

[[11 12  1]
 [13 14  2]
 [15 16  3]]


## Q#8: Print all elements of "newArray" using the loop.

In [11]:
for i in newArray:
    for j in range(newArray.shape[0]):
        print(i[j])

11
12
1
13
14
2
15
16
3


## Q#9: Reverse the columns and rows of "newArray".

In [12]:
for i in newArray:
    temp = i[0]
    i[0] = i[j]
    i[j] = temp
newArray



array([[ 1, 12, 11],
       [ 2, 14, 13],
       [ 3, 16, 15]])

## Q#10: Decrement all elements of "newArray" with 1.

In [13]:
for i in newArray:
    for j in range(newArray.shape[0]):
        i[j] = i[j] - 1
print(newArray)

[[ 0 11 10]
 [ 1 13 12]
 [ 2 15 14]]


## Q#11: Find smallest and biggest values in "newArray".

In [17]:
smallest = np.min(newArray)
biggest = np.max(newArray)
print(smallest,biggest)

0 15


## Q#12: Print the first row of "newArray" using indexing.

In [ ]:
newArray[0]

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [19]:
ind =np.where(newArray == 12)
newArray[ind]

array([12])

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [27]:
ind =np.where(newArray == 12)
ind2 = np.where(newArray == 0)
newArray[ind] , newArray[ind2]

array([[ 0, 11, 10],
       [ 1, 13, 12],
       [ 2, 15, 14]])

## Q#15: Change the shape of "newArray" to (9,1).

In [25]:
newArray.reshape(9,1)

array([[ 0],
       [11],
       [10],
       [ 1],
       [13],
       [12],
       [ 2],
       [15],
       [14]])

## Q#16: Change the shape of "newArray" to (3,2).

In [24]:
newArray.reshape(3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉