# Q1: Import numpy library

In [49]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [50]:
np.linspace(0, 1, 15)

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [51]:
arr1 = np.array([[1.1, 2.1, 3.1], 
[4.1, 5.1, 6.1]])

arr2 = np.array([[7.1, 8.1, 9.1], 
[10.1, 11.1, 12.1]])

arr= np.array([arr1, arr2])


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [52]:
arr.dtype, arr.shape, arr.size, arr.ndim


(dtype('float64'), (2, 2, 3), 12, 3)

# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [53]:
new_arr = arr.reshape(1, 2, 2, 3)
new_arr.shape , new_arr.ndim

((1, 2, 2, 3), 4)

# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [54]:
_4d_new_array = new_arr.astype(int)

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [55]:
for i in np.nditer(_4d_new_array
                   ):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [56]:
_4d_new_array[0,1,0,1]


8

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [57]:

_4d_new_array[0,0,1,1] ,_4d_new_array[0,0,1,2]




(5, 6)

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [58]:
ind = np.where(_4d_new_array ==8 )
_4d_new_array[ind]

array([8])

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [59]:
_4d_new_array.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [60]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
two  = np.concatenate((arr1, arr2)) 
two 

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [61]:
two  = np.concatenate((arr1, arr2),axis=1) 
two 

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [63]:
varr = np.vstack((arr1, arr2))
splited = np.split(varr, 2, axis=1)
splited

[array([['A'],
        ['E'],
        ['C'],
        ['G']], dtype='<U1'),
 array([['B'],
        ['F'],
        ['D'],
        ['H']], dtype='<U1')]