# Q1: Import numpy library

In [2]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [9]:
# Generate 15 numbers between 0 and 15
array = np.linspace(0, 15, num=15)
array

array([ 0.        ,  1.07142857,  2.14285714,  3.21428571,  4.28571429,
        5.35714286,  6.42857143,  7.5       ,  8.57142857,  9.64285714,
       10.71428571, 11.78571429, 12.85714286, 13.92857143, 15.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [10]:
# Define a 3D array with shape (2,2,3)

my_3d_array = np.array([
    [[1.1, 2.1, 3.1], [4.1, 5.1, 6.1]],  # First (2x3) block
    [[7.1, 8.1, 9.1], [10.1, 11.1, 12.1]] # Second (2x3) block
])

my_3d_array



array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [11]:

print("Array Type:", type(my_3d_array))

# Print array's elements datatype
print("Array Elements Data Type:", my_3d_array.dtype)

# Print array's shape
print("Array Shape:", my_3d_array.shape)

# Print array's size (total number of elements)
print("Array Size:", my_3d_array.size)

# Print array's number of dimensions
print("Array Dimensions:", my_3d_array.ndim)

Array Type: <class 'numpy.ndarray'>
Array Elements Data Type: float64
Array Shape: (2, 2, 3)
Array Size: 12
Array Dimensions: 3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [17]:
# Reshape the array to 4D (2,2,3,1)
my_4d_array = my_3d_array.reshape(2, 2, 3, 1)

print("New Array Dimension:", my_4d_array.ndim)
print("New Array Shape:", my_4d_array.shape)


New Array Dimension: 4
New Array Shape: (2, 2, 3, 1)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [15]:
# Convert array elements to integer
my_int_array = my_4d_array.astype(int)

print("New Integer Array:\n", my_int_array)

New Integer Array:
 [[[[ 1]
   [ 2]
   [ 3]]

  [[ 4]
   [ 5]
   [ 6]]]


 [[[ 7]
   [ 8]
   [ 9]]

  [[10]
   [11]
   [12]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [18]:
# Using nditer() to iterate over all elements
print("Array Elements:")
for element in np.nditer(my_int_array):
    print(element)

Array Elements:
1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [20]:
# Access number 8 using slicing
num_8 = my_int_array[1, 0, 1, 0]  # (2nd block, 1st row, 2nd column, 1st element)

num_8

8

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [21]:
# Access numbers 5 and 6 using slicing
num_5 = my_int_array[0, 1, 1, 0]  # (1st block, 2nd row, 2nd column, 1st element)
num_6 = my_int_array[0, 1, 2, 0]  # (1st block, 2nd row, 3rd column, 1st element)

print(num_5)
print(num_6)

5
6


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [22]:
# Search for number 8 using np.where()
index_path = np.where(my_int_array == 8)

print("Index path of number 8:", index_path)

Index path of number 8: (array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64), array([0], dtype=int64))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [30]:
# Reshape the array to (2,3,2)
reshaped_array = my_int_array.reshape(2, 3, 2)

print("Reshaped Array:\n", reshaped_array)
print("New Shape:", reshaped_array.shape)

Reshaped Array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
New Shape: (2, 3, 2)


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [32]:
# Given arrays
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

# Join the arrays 
joined_array = np.concatenate((arr1, arr2))
joined_array

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [34]:
# Join the arrays along rows usint axis = 1
joined_array = np.concatenate((arr1, arr2),axis=1)
joined_array

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [38]:
# Split the array into two along axis = 1
split_arrays = np.split(joined_array, 4, axis=1)

# Print the result of the split
print("Split Arrays:")
for i, arr in enumerate(split_arrays):
    print(f"Array {i+1}:\n", arr)

Split Arrays:
Array 1:
 [['A']
 ['E']]
Array 2:
 [['B']
 ['F']]
Array 3:
 [['C']
 ['G']]
Array 4:
 [['D']
 ['H']]
