# Q1: Import numpy library

In [1]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [5]:
sequence = np.linspace(0, 13, 15)  
print(sequence)

[ 0.          0.92857143  1.85714286  2.78571429  3.71428571  4.64285714
  5.57142857  6.5         7.42857143  8.35714286  9.28571429 10.21428571
 11.14285714 12.07142857 13.        ]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [8]:

arr1 = [1.1, 2.1, 3.1]
arr2 = [4.1, 5.1, 6.1]
arr3 = [7.1, 8.1, 9.1]
arr4 = [10.1, 11.1, 12.1]

array_3d = np.array([ [arr1, arr2], [arr3, arr4] ])

print("3D Array:")
print(array_3d)


3D Array:
[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [13]:
array_3D 
print("Array's Type:", type(array_3D))        
print("Array's Elements Datatype:", array_3D.dtype)  
print("Array's Shape:", array_3D.shape)       
print("Array's Size:", array_3D.size)         
print("Array's Dimension:", array_3D.ndim)    

Array's Type: <class 'numpy.ndarray'>
Array's Elements Datatype: float64
Array's Shape: (2, 2, 3)
Array's Size: 12
Array's Dimension: 3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [19]:
array_4D = array_3D.reshape(2, 2, 1, 3) 
print(array_4D)
print("")
print("New Array's Dimension:", array_4D.ndim)
print("New Array's Shape:", array_4D.shape)

[[[[ 1.1  2.1  3.1]]

  [[ 4.1  5.1  6.1]]]


 [[[ 7.1  8.1  9.1]]

  [[10.1 11.1 12.1]]]]

New Array's Dimension: 4
New Array's Shape: (2, 2, 1, 3)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [20]:
array_int = array_4D.astype(int)
print(array_int)

[[[[ 1  2  3]]

  [[ 4  5  6]]]


 [[[ 7  8  9]]

  [[10 11 12]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [21]:
for element in np.nditer(array_4D):
    print(element)

1.1
2.1
3.1
4.1
5.1
6.1
7.1
8.1
9.1
10.1
11.1
12.1


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [22]:
number_8 = array_4D[1, 0, 0, 1] 
print(number_8)

8.1


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [23]:
numbers_5_6 = array_4D[0, 1, 0, 1:3]
numbers_5_6

array([5.1, 6.1])

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [25]:
index_8 = np.where(array_4D == 8)
print("Index Path to Number 8:", index_8)

Index Path to Number 8: (array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [26]:
reshaped_array = array_4D.reshape(2, 3, 2)
reshaped_array

array([[[ 1.1,  2.1],
        [ 3.1,  4.1],
        [ 5.1,  6.1]],

       [[ 7.1,  8.1],
        [ 9.1, 10.1],
        [11.1, 12.1]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [31]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

joined_array = np.concatenate((arr1, arr2), axis=None)
joined_array

array(['A', 'B', 'E', 'F', 'C', 'D', 'G', 'H'], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [32]:
joined_array = np.concatenate((arr1, arr2), axis=1)  


print("Joined Array:\n", joined_array)

Joined Array:
 [['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [33]:
split_arrays = np.split(joined_array, 2, axis=1)  

print("First Split Array:\n", split_arrays[0])
print("Second Split Array:\n", split_arrays[1])

First Split Array:
 [['A' 'B']
 ['E' 'F']]
Second Split Array:
 [['C' 'D']
 ['G' 'H']]
