In [3]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [5]:
x = np.ones((2, 2))
print (x)

[[1. 1.]
 [1. 1.]]


## Q#2: Create y array with elements equal to 0.

In [8]:
y = np.zeros(2,1)
print(y)

TypeError: Cannot interpret '1' as a data type

## Q#3: Add x and y arrays.

In [10]:
z = x + y 
print(z)

[[1. 1.]
 [1. 1.]]


## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [ ]:
print("Dimension:", x.ndim) 
print("Shape:", x.shape)      
print("Size:", x.size)        
print("Type:", type(x))       

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [11]:
me = np.array([[11, 12],
              [13, 14],
              [15, 16]])  
print(me)

[[11 12]
 [13 14]
 [15 16]]


## Q#6: Create z array contains the numbers from 1 to 3.

In [13]:
z = np.array([1, 2, 3]) 
print(z)

[1 2 3]


## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [15]:
newvariable = np.hstack((z.reshape(-1, 1), me))

## Q#8: Print all elements of "newArray" using the loop.

In [16]:
for i in newvariable.flat:  # Iterate through all elements
    print(i) 

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [ ]:
reversed = np.flipud(np.fliplr(newvariable))  

## Q#10: Decrement all elements of "newArray" with 1.

In [ ]:
newvariable -= 1 

## Q#11: Find smallest and biggest values in "newArray".

In [17]:
smallest = np.min(newvariable)
biggest = np.max(newvariable)  
print(smallest)
print(biggest)

1
16


## Q#12: Print the first row of "newArray" using indexing.

In [22]:
print(newvariable[0]) 

[ 1 11 12]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [20]:
print(newvariable[newvariable == 12]) 

[12]


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [24]:
k = np.isin(newvariable, [0, 13]) 
print("Numbers 0 and 13:", newvariable[k])

Numbers 0 and 13: [13]


## Q#15: Change the shape of "newArray" to (9,1).

In [23]:
newArray_reshaped_9_1 = newvariable.reshape(9, 1)


## Q#16: Change the shape of "newArray" to (3,2).

In [ ]:
newArr_reshaped = newvariable.reshape(3, 2)

# Well Done 🎉