In [2]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [3]:
# We use a ones funcrion to return ones elements and pass 2 that mean we need 2 elements in the array 
x = np.ones(2)
x

array([1., 1.])

## Q#2: Create y array with elements equal to 0.

In [5]:
# We use a Zeros funcrion to return zeros elements and pass 2 that mean we need 2 elements in the array 
y = np.zeros(2)
y

array([0., 0.])

## Q#3: Add x and y arrays.

In [6]:
# To add to arrays we just ues + operation
x + y

array([1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [13]:
# We use ndim attribute that returns an integer that tells us how many dimensions the array have.
print(f"The number of Dimension: {x.ndim}")
# And use shape attribute to get the shape info 
print(f"The Shape is: {x.shape}")
# To get the size we use size attribute to get the shape info 
print(f"The Size is: {x.size}")
# We use dtype that returns the data type of the array
print(f"The Data Type is: {x.dtype}")

The number of Dimension: 1
The Shape is: (2,)
The Size is: 2
The Data Type is: float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [17]:
# We Creat a 2D arry using [[row1],[row2],[row3]]
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [22]:
# We use arange function to return a numbers from 1 to 3
z = np.arange(1,4)   # np.arange(start_num,stop_num) 
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [34]:
# We use a hstack function to combine tow arrys horizontal

# newArry = np.hstack((z,w))

## The will sohw in Error becuse all arrays must have the same number of dimensions 
### W is 2D array 
### Z is 1D array

# To solve this we will reshape Z arry to be 2D array:
z = z.reshape(3, 1)
# Then try agine it will work 
newArry = np.hstack((z,w))
newArry



array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [41]:
# We can use a simple loop in another loop
# for x in newArry:
#     for y in x:
#         print(y)
##

## or we can use list comprehension to create a list and print it element by element
[(print(y)) for x in newArry for y in x]

1
11
12
2
13
14
3
15
16


[None, None, None, None, None, None, None, None, None]

## Q#9: Reverse the columns and rows of "newArray".

In [43]:
# We will use T attribute to Reverse the columns and rows
newArry.T

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [61]:
# With simple way just i use - operation

newArry = newArry - 1

## Q#11: Find smallest and biggest values in "newArray".

In [62]:
# Use a max(),min() functions to get the smallest and biggest values  
print(newArry.min())

print(newArry.max())

0
15


## Q#12: Print the first row of "newArray" using indexing.

In [63]:
# When we access a array by indexing we can use: array_name[row,column]
print(newArry[0])

[ 0 10 11]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [64]:
print(newArry)

[[ 0 10 11]
 [ 1 12 13]
 [ 2 14 15]]


In [69]:
# When we access a array by indexing we can use: array_name[row,column]

print(newArry[1,1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [74]:
# When we access a array by indexing we can use: array_name[row,column]

print(newArry[0,0],)

print(newArry[1,2])




0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [77]:
# Using reshape funtion 
newArry = newArry.reshape(9,1)
newArry

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [78]:
# Reshaping newArray to (3,2) is not possible because it currently contains 9 elements.
newArry = newArry.reshape(3,2)
newArry

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉