In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [7]:
# write your code here ^_^
x=np.ones(7)
x

array([1., 1., 1., 1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [8]:
# write your code here ^_^
y=np.zeros(7)
y

array([0., 0., 0., 0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [32]:
# write your code here ^_^
add=x+y
add

array([1., 1., 1., 1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [15]:
# write your code here ^_^
print(x.ndim)
print(x.shape)
print(x.size)
print(type(x))

1
(7,)
7
<class 'numpy.ndarray'>


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [83]:
# write your code here ^_^
w=np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [103]:
# write your code here ^_^
z=np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [115]:
# write your code here ^_^

# we can do not directly we must reshape the array to the same dimensions
z=z.reshape(3,1)
w=w.reshape(3,2)
newArray=np.hstack((z,w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [116]:
# write your code here ^_^
for i in newArray:
    print(i)

[ 1 11 12]
[ 2 13 14]
[ 3 15 16]


## Q#9: Reverse the columns and rows of "newArray".

In [161]:
# write your code here ^_^
newArray=newArray[::-1,::-1]
newArray

array([[16, 15,  3],
       [14, 13,  2],
       [12, 11,  1]])

## Q#10: Decrement all elements of "newArray" with 1.

In [162]:
# write your code here ^_^
newArray=newArray-1
newArray

array([[15, 14,  2],
       [13, 12,  1],
       [11, 10,  0]])

## Q#11: Find smallest and biggest values in "newArray".

In [163]:
# write your code here ^_^
n=newArray.min()
m=newArray.max()

print(f"the smallest value is ({n}) and the bigest valueis ({m})")



the smallest value is (0) and the bigest valueis (15)


## Q#12: Print the first row of "newArray" using indexing.

In [164]:
# write your code here ^_^
newArray[:1]

array([[15, 14,  2]])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [168]:
# write your code here ^_^
print(newArray[1,1])

np.int64(12)

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [173]:
# write your code here ^_^
print(newArray[2,2])
print(newArray[1,0])

0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [174]:
# write your code here ^_^
newArray=newArray.reshape(9,1)
newArray

array([[15],
       [14],
       [ 2],
       [13],
       [12],
       [ 1],
       [11],
       [10],
       [ 0]])

## Q#16: Change the shape of "newArray" to (3,2).

In [175]:
# write your code here ^_^
newArray=newArray.reshape(3,2)
newArray

# I can't change the shape of "newArray" because the 3*2 != 9*1 

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉