In [11]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [15]:
# write your code here ^_^


x = np.ones(3)
x

array([1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [16]:
# write your code here ^_^
y = np.zeros(3)
y

array([0., 0., 0.])

## Q#3: Add x and y arrays.

In [17]:
# write your code here ^_^

z = x + y
z

array([1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [18]:
# write your code here ^_^
print(x.ndim)
print(x.shape)
print(x.size)
x.dtype

1
(3,)
3


dtype('float64')

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [31]:
# write your code here ^_^
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [24]:
# write your code here ^_^

z = np.array([1,2,3])
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [81]:
# write your code here ^_^
z = z.reshape(-1, 1)
newArray = np.hstack((z, w))
newArray


array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [82]:
# write your code here ^_^
for i in newArray:
    print(i)

[ 1 11 12]
[ 2 13 14]
[ 3 15 16]


## Q#9: Reverse the columns and rows of "newArray".

In [83]:
# write your code here ^_^
newArray = np.flip(newArray)
newArray

array([[16, 15,  3],
       [14, 13,  2],
       [12, 11,  1]])

## Q#10: Decrement all elements of "newArray" with 1.

In [84]:
# write your code here ^_^
newArray = newArray -1
newArray

array([[15, 14,  2],
       [13, 12,  1],
       [11, 10,  0]])

## Q#11: Find smallest and biggest values in "newArray".

In [85]:
# write your code here ^_^
print(newArray.max())
print(newArray.min())


15
0


## Q#12: Print the first row of "newArray" using indexing.

In [86]:
# write your code here ^_^
newArray[0]

array([15, 14,  2])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [89]:
# write your code here ^_^

newArray[[1],[1]]

array([12])

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [92]:
# write your code here ^_^

print(newArray[[2],[2]])
print(newArray[[1],[0]])

[0]
[13]


## Q#15: Change the shape of "newArray" to (9,1).

In [93]:
# write your code here ^_^
newArray.reshape(9,1)

array([[15],
       [14],
       [ 2],
       [13],
       [12],
       [ 1],
       [11],
       [10],
       [ 0]])

## Q#16: Change the shape of "newArray" to (3,2).

In [94]:
# write your code here ^_^
newArray.reshape(3,2)


ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉