# Q1: Import numpy library

In [100]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [101]:
a = np.linspace(0,15,15)
a

array([ 0.        ,  1.07142857,  2.14285714,  3.21428571,  4.28571429,
        5.35714286,  6.42857143,  7.5       ,  8.57142857,  9.64285714,
       10.71428571, 11.78571429, 12.85714286, 13.92857143, 15.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [102]:
arr1 = [1.1, 2.1, 3.1]
arr2 = [4.1, 5.1, 6.1]
arr3 = [7.1, 8.1, 9.1]
arr4 = [10.1, 11.1, 12.1]

sArray = np.array([[arr1,arr2],[arr3,arr4]])
sArray

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [103]:
sArray.dtype
for row in sArray:
    for element in sArray:
        print(sArray.dtype)
print(sArray.shape)
print(sArray.size)
print(sArray.ndim)

float64
float64
float64
float64
(2, 2, 3)
12
3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [104]:
newArray = np.array([sArray,sArray])
print("------------------")
print(newArray)
print("------------------")
newArray.ndim , newArray.shape

------------------
[[[[ 1.1  2.1  3.1]
   [ 4.1  5.1  6.1]]

  [[ 7.1  8.1  9.1]
   [10.1 11.1 12.1]]]


 [[[ 1.1  2.1  3.1]
   [ 4.1  5.1  6.1]]

  [[ 7.1  8.1  9.1]
   [10.1 11.1 12.1]]]]
------------------


(4, (2, 2, 2, 3))

# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [105]:
arrayType = newArray.astype(np.int32)
arrayType

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [106]:
for row in arrayType:
    for element in np.nditer(arrayType):
        print(f"- {element} - ")

- 1 - 
- 2 - 
- 3 - 
- 4 - 
- 5 - 
- 6 - 
- 7 - 
- 8 - 
- 9 - 
- 10 - 
- 11 - 
- 12 - 
- 1 - 
- 2 - 
- 3 - 
- 4 - 
- 5 - 
- 6 - 
- 7 - 
- 8 - 
- 9 - 
- 10 - 
- 11 - 
- 12 - 
- 1 - 
- 2 - 
- 3 - 
- 4 - 
- 5 - 
- 6 - 
- 7 - 
- 8 - 
- 9 - 
- 10 - 
- 11 - 
- 12 - 
- 1 - 
- 2 - 
- 3 - 
- 4 - 
- 5 - 
- 6 - 
- 7 - 
- 8 - 
- 9 - 
- 10 - 
- 11 - 
- 12 - 


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [107]:
arrayType[0,1,0,1]

8

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [108]:
arrayType[0,0,1,1:3], 

(array([5, 6]),)

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [109]:
indices = np.where(arrayType == 8)
print(indices)


(array([0, 1], dtype=int64), array([1, 1], dtype=int64), array([0, 0], dtype=int64), array([1, 1], dtype=int64))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [110]:
subArray = arrayType[:1]
reshapedArray = subArray.reshape(2, 3, 2)

reshapedArray

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [111]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

joinArray = np.concatenate((arr1, arr2))

print(joinArray)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [112]:
joinArray1 = np.concatenate((arr1, arr2), axis=1)

print(joinArray1)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [113]:
splitArray = np.split(joinArray1, 2, axis=1)

splitArray

[array([['A', 'B'],
        ['E', 'F']], dtype='<U1'),
 array([['C', 'D'],
        ['G', 'H']], dtype='<U1')]