In [2]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [7]:
x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [8]:
y = np.zeros(5)
y

array([0., 0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [9]:
z = x + y
z

array([1., 1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [91]:
x.ndim, x.shape, x.size, type(x), x.dtype

(1, (5,), 5, numpy.ndarray, dtype('float64'))

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [13]:
w = np.array([[11, 12], [13, 14], [15, 16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [29]:
z = np.arange(1, 4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [50]:
newArray = np.hstack((z.reshape((-1, 1)), w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [47]:
for sublist in newArray:
    for item in sublist:
        print(item)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [51]:
newArray = newArray[::-1, ::-1]
newArray

array([[16, 15,  3],
       [14, 13,  2],
       [12, 11,  1]])

## Q#10: Decrement all elements of "newArray" with 1.

In [52]:
newArray = newArray - 1

In [53]:
newArray

array([[15, 14,  2],
       [13, 12,  1],
       [11, 10,  0]])

## Q#11: Find smallest and biggest values in "newArray".

In [56]:
min, max = int(np.min(newArray)), int(np.max(newArray))
min, max

(0, 15)

## Q#12: Print the first row of "newArray" using indexing.

In [57]:
newArray[0:1, ]

array([[15, 14,  2]])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [61]:
print(newArray[1, 1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [60]:
print(newArray[2, 2], newArray[1, 0])


0 13


## Q#15: Change the shape of "newArray" to (9,1).

In [86]:
newArray = newArray.reshape(-1, 1)
newArray

array([[15],
       [14],
       [ 2],
       [13],
       [12],
       [ 1],
       [11],
       [10],
       [ 0]])

## Q#16: Change the shape of "newArray" to (3,2).

In [88]:
# The original newArray is (9,1) with 9 elements.
# Since (3,2) requires 6 elements, we remove the last 3 elements
# newArray[:6] keeps only the first 6 elements.
newArray[:6].reshape((3, 2))

array([[15, 14],
       [ 2, 13],
       [12,  1]])

In [89]:
# The question asks for (3,2), but newArray originally has 9 elements.
# Reshaping to (3,2) is impossible without losing elements.
# Assuming a mistake in the question, we reshape to (3,3), which keeps all elements intact.
newArray.reshape((3, 3))

array([[15, 14,  2],
       [13, 12,  1],
       [11, 10,  0]])

# Well Done 🎉