# Q1: Import numpy library

In [1]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [7]:
# write your code here ^_^
seq=np.linspace(0,5,15)
print(seq)

[0.         0.35714286 0.71428571 1.07142857 1.42857143 1.78571429
 2.14285714 2.5        2.85714286 3.21428571 3.57142857 3.92857143
 4.28571429 4.64285714 5.        ]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [9]:
# write your code here ^_^
arr1 =np.array([1.1,2.1,3.1])
arr2 =np.array([4.1,5.1,6.1])
arr3 =np.array([7.1,8.1,9.1])
arr4 =np.array([10.1,11.1,312.1])
array1 = np.array([[arr1, arr2], [arr3, arr4]])
print(array1)


[[[  1.1   2.1   3.1]
  [  4.1   5.1   6.1]]

 [[  7.1   8.1   9.1]
  [ 10.1  11.1 312.1]]]


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [13]:
# write your code here ^_^
print(array1)
print(type(array1))
print(array1.shape)
print(array1.size)
print(array1.ndim)

[[[  1.1   2.1   3.1]
  [  4.1   5.1   6.1]]

 [[  7.1   8.1   9.1]
  [ 10.1  11.1 312.1]]]
<class 'numpy.ndarray'>
(2, 2, 3)
12
3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [23]:
# write your code here ^_^

array2=array1.reshape(1, 2, 2, 3)
print(array2)
print(array2.ndim)
print(array2.shape)

[[[[  1.1   2.1   3.1]
   [  4.1   5.1   6.1]]

  [[  7.1   8.1   9.1]
   [ 10.1  11.1 312.1]]]]
4
(1, 2, 2, 3)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [24]:
# write your code here ^_^
new_array= array2.astype(int)
print(new_array)

[[[[  1   2   3]
   [  4   5   6]]

  [[  7   8   9]
   [ 10  11 312]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [26]:
# write your code here ^_^
new_array
for i in np.nditer(new_array):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
312


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [35]:
# write your code here ^_^
print(new_array)
print(new_array[0][1][0][1])


[[[[  1   2   3]
   [  4   5   6]]

  [[  7   8   9]
   [ 10  11 312]]]]
8


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [36]:
# write your code here ^_^
print(new_array[0, 0, 1, 1]) 
print(new_array[0, 0, 1, 2])

5
6


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [37]:
# write your code here ^_^
new_array
y=np.where(new_array ==8)
y

(array([0]), array([1]), array([0]), array([1]))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [38]:
# write your code here ^_^
new_array.reshape((2, 3, 2))

array([[[  1,   2],
        [  3,   4],
        [  5,   6]],

       [[  7,   8],
        [  9,  10],
        [ 11, 312]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [44]:
# write your code here ^_^
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
join_a = np.concatenate((arr1, arr2))
print(join_a)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [46]:
# write your code here ^_^
join_1=np.concatenate((arr1, arr2), axis=1)
join_1

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [47]:
# write your code here ^_^
np.split(join_a, 2, axis=1)

[array([['A'],
        ['E'],
        ['C'],
        ['G']], dtype='<U1'),
 array([['B'],
        ['F'],
        ['D'],
        ['H']], dtype='<U1')]