# Q1: Import numpy library

In [1]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [2]:
# write your code here ^_^
sequence = np.linspace(0, 10, 15)

print(sequence)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [3]:
# write your code here ^_^

arr1 = [1.1, 2.1, 3.1]
arr2 = [4.1, 5.1, 6.1]
arr3 = [7.1, 8.1, 9.1]
arr4 = [10.1, 11.1, 12.1]

result = np.array([ [arr1, arr2], [arr3, arr4] ])

print(result)


[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [4]:
# write your code here ^_^
print("Array's type:", type(result))
print("Array's elements datatype:", result.dtype)
print("Array's shape:", result.shape)
print("Array's size:", result.size)
print("Array's dimension:", result.ndim)

Array's type: <class 'numpy.ndarray'>
Array's elements datatype: float64
Array's shape: (2, 2, 3)
Array's size: 12
Array's dimension: 3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [5]:
# write your code here ^_^
new_array = result.reshape(1, 2, 2, 3)

print("New array's dimension:", new_array.ndim)
print("New array's shape:", new_array.shape)

New array's dimension: 4
New array's shape: (1, 2, 2, 3)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [6]:
# write your code here ^_^
new_array_int = new_array.astype(int)


print("New array with integer data type:\n", new_array_int)

New array with integer data type:
 [[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [7]:
# write your code here ^_^
for element in np.nditer(new_array_int):
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [8]:
# write your code here ^_^
print(new_array_int[0, 1, 0, 1])

8


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [9]:
# write your code here ^_^
print(new_array_int[0, 0, 1, 1],new_array_int[0, 0, 1, 2]) 

5 6


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [10]:
# write your code here ^_^
indices = np.where(new_array_int == 8)

print("Indices of number 8:", indices)

Indices of number 8: (array([0]), array([1]), array([0]), array([1]))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [11]:
# write your code here ^_^
reshaped_array = new_array_int.reshape(2, 3, 2)

print(reshaped_array)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [12]:
# write your code here ^_^
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

joined_array = np.concatenate((arr1, arr2))

print(joined_array)

[['A' 'B']
 ['E' 'F']
 ['C' 'D']
 ['G' 'H']]


# Q12.2: Join the arrays along rows with axis = 1 

In [13]:
# write your code here ^_^
joined_array = np.concatenate((arr1, arr2), axis=1)

print(joined_array)

[['A' 'B' 'C' 'D']
 ['E' 'F' 'G' 'H']]


# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [14]:
# write your code here ^_^
split_arrays = np.hsplit(joined_array, 2)


print("First split array:")
print(split_arrays[0])

print("\nSecond split array:")
print(split_arrays[1])

First split array:
[['A' 'B']
 ['E' 'F']]

Second split array:
[['C' 'D']
 ['G' 'H']]
