In [1]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [3]:
# write your code here ^_^
x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [4]:
# write your code here ^_^
y = np.zeros(5)
y

array([0., 0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [5]:
# write your code here ^_^
x + y

array([1., 1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [14]:
# write your code here ^_^
print("the dimension of x is ",x.ndim)
print("The shape of x is ", x.shape)
print("The size of x is ", x.size)
print("The type of x is ", type(x))
print("The data type of x is ", x.dtype)

the dimension of x is  1
The shape of x is  (5,)
The size of x is  5
The type of x is  <class 'numpy.ndarray'>
The data type of x is  float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [33]:
# write your code here ^_^
w = np.array([[11, 12], [13, 14], [15, 16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [24]:
# write your code here ^_^
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [34]:
# write your code here ^_^
#changed the the chape of z from (1,3) to (3,1) to stack it horizontally on w which has the shape of (3,2)
newArray = np.hstack((z, w))
z = z.reshape(-1,1) 
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [50]:
# write your code here ^_^
#there are different way to loop through 2D arrays some of them are the following:

for row in range(newArray.shape[0]):
    for col in range(newArray.shape[1]):
        print(newArray[row,col])
        
print('\n')

for row in newArray:
    for value in row:
        print(value)

1
11
12
2
13
14
3
15
16


1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [61]:
# write your code here ^_^
reversedArray = np.flip(newArray)
reversedArray

array([[16, 15,  3],
       [14, 13,  2],
       [12, 11,  1]])

## Q#10: Decrement all elements of "newArray" with 1.

In [63]:
# write your code here ^_^
newArray = newArray - 1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [64]:
# write your code here ^_^
newArray.min()

0

## Q#12: Print the first row of "newArray" using indexing.

In [65]:
# write your code here ^_^
print(newArray[0,])

[ 0 10 11]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [67]:
# write your code here ^_^
print(newArray[1,1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [69]:
# write your code here ^_^
print(newArray[0,0])
print(newArray[1,2])

0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [70]:
# write your code here ^_^
newArray.reshape(9,1)

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [86]:
# write your code here ^_^
#newArray.reshape(3,2)
#It cannot be dirctly reshaped into (3,2) because this shape requires 6 elements and newArray includes 9 elements

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉