# Q1: Import numpy library

In [1]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [13]:
# write your code here ^_^
np.linspace(0.0, 15.0, num=15, dtype=float)

array([ 0.        ,  1.07142857,  2.14285714,  3.21428571,  4.28571429,
        5.35714286,  6.42857143,  7.5       ,  8.57142857,  9.64285714,
       10.71428571, 11.78571429, 12.85714286, 13.92857143, 15.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [20]:
# write your code here ^_^
q3 = np.array([[[1.1, 2.1, 3.1], [4.1, 5.1, 6.1]], [[7.1, 8.1, 9.1], [10.1, 11.1, 12.1]]])
q3

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [25]:
# write your code here ^_^
print("Array's type: ",type(q3))
print("Array's elements data type:", q3.dtype)
print("Array's shape: ", q3.shape)
print("Array's size: ", q3.size)
print("Array's dimension: ", q3.ndim)

Array's type:  <class 'numpy.ndarray'>
Array's elements data type: float64
Array's shape:  (2, 2, 3)
Array's size:  12
Array's dimension:  3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [34]:
# write your code here ^_^
q5 = q3.reshape(2,2,3,1)
print(q5)

[[[[ 1.1]
   [ 2.1]
   [ 3.1]]

  [[ 4.1]
   [ 5.1]
   [ 6.1]]]


 [[[ 7.1]
   [ 8.1]
   [ 9.1]]

  [[10.1]
   [11.1]
   [12.1]]]]


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [37]:
# write your code here ^_^
q6 = q5.astype(int)
print(q6)

[[[[ 1]
   [ 2]
   [ 3]]

  [[ 4]
   [ 5]
   [ 6]]]


 [[[ 7]
   [ 8]
   [ 9]]

  [[10]
   [11]
   [12]]]]


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [44]:
# write your code here ^_^
for element in np.nditer(q6): #by default the order is set to row-amjor order
    print(element)
    
print('\n')

for element in np.nditer(q6, order='F'): # F is used to set the order to column-major order
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12


1
7
4
10
2
8
5
11
3
9
6
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [120]:
# write your code here ^_^
print(q6[1:2, 0:1, 1:2, 0:1])  #used slicing for each dimension and returned 
#squeeze npumy method remove a single-dimensional entry from the array shape
print(q6[1:2, 0:1, 1:2, 0:1].squeeze()) #googled a numpy method that can help returning a number out of the dimension


[[[[8]]]]
8


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [143]:
# write your code here ^_^
print(q6[0:1, 1:2, 2:3, 0:1])
print(q6[0:1, 1:2, 2:3, 0:1].squeeze())
print('\n')
print(q6[0:1, 1:2, 1:2, 0:1])
print(q6[0:1, 1:2, 1:2, 0:1].squeeze())

[[[[6]]]]
6


[[[[5]]]]
5


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [151]:
index_path = np.where(q6 == 8)
print(index_path)

(array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64), array([0], dtype=int64))


In [148]:
# write your code here ^_^
condition = q6 == 8
result = np.where(condition, True, q6)
result

array([[[[ 1],
         [ 2],
         [ 3]],

        [[ 4],
         [ 5],
         [ 6]]],


       [[[ 7],
         [ 1],
         [ 9]],

        [[10],
         [11],
         [12]]]])

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [163]:
# write your code here ^_^
q11 = q6.reshape(2, 3, 2)
q11

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [171]:
# write your code here ^_^
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
joined = np.vstack((arr1, arr2))
joined

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [172]:
# write your code here ^_^
np.hstack((arr1, arr2))

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [175]:
# write your code here ^_^
splited = np.split(joined, 2, axis=1)
splited

[array([['A'],
        ['E'],
        ['C'],
        ['G']], dtype='<U1'),
 array([['B'],
        ['F'],
        ['D'],
        ['H']], dtype='<U1')]